version: "3.3"

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    restart: on-failure
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: $DB_URL
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
volumes:
  db:
